baseURL = 'https://ditio.org'
languageCode = 'no-nb'
title = 'Ditio'
theme = 'console'

pluralizelisttitles = "false"
enableRobotsTXT = true

[params]
  # Cutting off the page title to two chars for mobile (console-demo -> co)
  titleCutting = false
  title = "Ditio - Linjeforeningen"
  description = 'Linjeforeningen for alle linjene som hører til under insitutt for informasjonsteknologi på OsloMet og andre interessenter. Ditio sitt formål å være en sosial og faglig forening for foreningens medlemmer.'
  image = "/img/logo-rectangle-wide.png"

  # Set the animation style -- https://animate.style/
  # To disable animations, please remove or comment animationStyle parameter
  animateStyle = "animated zoomIn fast"

  [[params.navlinks]]
  name = "arrangementer/"
  url = "arrangementer/"

  [[params.navlinks]]
  name = "om oss/"
  url = "om_oss/"

#  Ikke i bruk akkurat nå
#  [[params.navlinks]]
#  name = "bilder/"
#  url = "photos/"
