baseURL = 'http://example.org'
languageCode = 'no-nb'
title = 'D.IT-I/O'
theme = 'console'

pluralizelisttitles = "false"

[params]
  # Cutting off the page title to two chars for mobile (console-demo -> co)
  titleCutting = false

  # Set the animation style -- https://animate.style/
  # To disable animations, please remove or comment animationStyle parameter
  animateStyle = "animated zoomIn fast"

  [[params.navlinks]]
  name = "arrangementer/"
  url = "arrangementer/"

  [[params.navlinks]]
  name = "om oss/"
  url = "om_oss/"

#  Ikke i bruk akkurat nå
  [[params.navlinks]]
  name = "bilder/"
  url = "photos/"
